### ISSUE TITLE
jsonld_context should also be a class method

### ISSUE THREAD

**Issue by dchandekstark** [mtrudel/pragmatic_context#8]
It's not dependent on instance attributes, and it's awkward to instantiate a model in order to produce a context document -- e.g. to serve at a URL, so that API responses can use the Link header instead of embedding the context.

**Comment by mtrudel** [comment]
It *can8 be dependent on the object in the case of a custom contextualizer (in fact, this is the specific use case that I depend on prag_con for in my own work). However, I totally see (and agree with) the fact that the use case you suggest should also be fully supported.  

I think that it should be a pretty quick workup; let me bat some ideas around this weekend and see what I come up with. In the meantime, if you've got ideas, I'm more than happy to entertain a PR :)

**Comment by dchandekstark** [comment]
OK, I thought there was probably a reason. I can deal with it while you consider the alternatives.

**Comment by mtrudel** [comment]
Check the commit above; I've added support into the default contextualizer to return all defined terms like so (assuming this is defined on a `Document` class):

    Document.contextualizer.definitions_for_terms

will return you a Hash containing the context for all known fields defined on the `Document` model. I *think* that's what you need, but please let me know if it falls short in some way, or isn't otherwise ideal for you!

**Comment by mtrudel** [comment]
Also, let me know if it works for you so I can close this issue.

**Comment by dchandekstark** [comment]
Yep, that works great.  Cool thing, too, is you can keep the context in a separate class from the model.  Feel free to close the issue. Thanks!

**Comment by mtrudel** [comment]
Super. Glad to be of service!
